services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3_data:/data
  # This service just make sure a bucket with the right policies is created
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/manim;
      /usr/bin/mc anonymous set public minio/manim/public;
      exit 0;
      "
  # Kafka service for Manim integration
  kafka_service:
    image: apache/kafka:latest
    container_name: manim_kafka
    ports:
      - "9092:9092"
    env_file:
      - .env
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_HOST_IP}:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
  # Kafka topic creation
  kafka_create_topic:
    image: apache/kafka:latest
    depends_on:
      - kafka_service
    entrypoint: >
      bash -c "
      sleep 20 && /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server ${KAFKA_HOST_IP}:9092 --replication-factor 1 --partitions 3 --topic manim-topic"

  # Database for Manim integration
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: manimdb
      POSTGRES_DB: manimdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  s3_data:
  db_data:
