name: Check build on PR
on:
  pull_request:
    branches:
      - "**"
    paths:
      - "main-app/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: main-app
    env:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/mydb

    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Drizzle generate

        run: bun run db:generate

      - name: Build
        run: bun run build
